### ISSUE TITLE
Obd class not found

### ISSUE THREAD

**Issue by invweb** [Tomiwa-Ot/obd#4]
added to the gradle:
implementation 'com.github.Tomiwa-Ot.obd:obd:1.21'
The Obd class was not found. When trying to add it manually, this file is not found.

**Comment by invweb** [comment]
Help!!

**Comment by invweb** [comment]
![Screenshot 2024-12-27 at 22 09 50](https://github.com/user-attachments/assets/e549a0e6-a477-4654-8d57-9df44b8c89f8)
![Screenshot 2024-12-27 at 22 09 38](https://github.com/user-attachments/assets/b4ad5681-eb34-4ba1-98e5-c4ea48901f83)

**Comment by Tomiwa-Ot** [comment]
![image](https://github.com/user-attachments/assets/efaded43-79fa-4a88-9133-60f22af2df25)

Add line 5 and 14 in the image above to settings.gradle
